# Introduction to Julia

* Julia is a high-level programming language for technical computing which allows you to manipulate and analyse large data sets

## Interesting features:
 * Julia is build from the ground for techical computing. 
 * The language is close to the mathematical notation, for example to define a function $f(x) = 2x + 3$ in Julia is:

```julia
f(x) = 2x + 3
```
  
 * Julia is free and open-source software.
 * Julia's code is compiled to machine code and loops can be as fast as in other compiled languages (like Fortran or C)


## Instructions for installing Julia on your laptop

* If you want to install Julia on your laptop later on, here are some instructions
* Go to http://julialang.org/downloads/
* There are various editor with support for Julia (like atom, notepad++, emacs, vim...)

### Ways to run Julia:

#### Command line

* Use the `Tab` key to complete file, variable and function names
* `Up` and `down arrows` key to repeat a previously entered command
* `Control-R` to search a command
* On Windows enable "[quick edit](https://www.tekrevue.com/tip/boost-productivity-quickedit-mode-windows-command-prompt/)" for easier copy and pasting
![cmd](Fig/julia-commandline.png)

#### Jupyter notebook (web-browser)

* Web-interface for Julia (among others)
* The Julia package `IJulia` which also installs Jupyter http://jupyter.org/
* Various [keyboard short cuts](https://www.cheatography.com/weidadeyue/cheat-sheets/jupyter-notebook/) are defined to be productive with jupyter notebooks
* General documentation of [Jupyter Notebooks](http://jupyter-notebook.readthedocs.io)

![cmd](Fig/julia-jupyter.png)

Text can be formatted using markdown.

# Markdown

This is an explanation
* item one
* item two
   * sub item one
   * sub item two
$$ c^2 = a^2 + b^2 $$ 
   

#### Juno

* Based on the Atom editor from GitHub
* Integrates an editor, command line and documentation browser
* Available from http://junolab.org/

![atom](Fig/julia-atom.png)

# Julia documentation

* The manual: https://docs.julialang.org
* Tutorials and books: https://julialang.org/learning/


## Comparision with other languages


* [Noteworthy Differences from other Languages](https://docs.julialang.org/en/stable/manual/noteworthy-differences/)
* [MATLAB–Python–Julia cheatsheet](https://cheatsheets.quantecon.org/)





# First steps in Julia

## Numbers

* Use a dot (.) as decimal separator (e.g. 3.14 and not 3,14)
* You can use the scientific notation $a \times 10^{-b}$ using the e-notation. (e.g. $3 \times10^{-7}$ becomes 3e-7) 
* Use Julia as a calculator:

In [7]:
1 + 3 * 4/2 

7.0

* The usual operator precedence applies


## Useful constants

Various constants are also pre-defined: π (pi), e (Euler's number), im (the imaginary number), Inf (Infinity, result from e.g. 1/0) and NaN (Not a Number - result from e.g. 0/0)



## Variables

* Numbers (and any other data type) can be put into variables
* The value of a variable is referenced by its name
* A variable name can be composed by letters (a-z and A-Z, including greek letters, accents,...), numbers (0-9), underscore (_) and some unicode symbols (like greek letters). The first character cannot be a number.

* Example:

In [8]:
temp = 21

21

To see the content of the variable `temp`:

In [9]:
@show temp

temp = 21


21

Any expression can now include the variable `temp`:

In [10]:
2 * temp


42

* The variable `temp` has now the value 21. The value of the variable can be changed later on.
* An assignment without a final semicolon echos its value to the screen
* Careful: the value of constants can be overwritten. The following is allowed but not encouraged:
    	
```julia        
    pi = 3; # do not do this
```

* The command `whos()` lists the currently defined variables and their size. 

## Strings

* Delimited by double quotes
    	

In [11]:
s = "Hello world"
print(s)

Hello world

* How to use a double quote in a string? -> place a backslash in front:

In [12]:
s = "The letter \"A\" is the first letter of the alphabet."
print(s)

The letter "A" is the first letter of the alphabet.

## Symbols

* A symbol is an [interned string](https://en.wikipedia.org/wiki/String_interning) identifier which means that every  string symbol is replaced internally by a number

* This makes comparision between symbols faster than comparision between strings
* Symbols are also used in metaprogramming (julia code which produces julia code).

In [13]:
:mysymbol

:mysymbol

## Vectors and matrices

* Vectors are list of numbers. The column vector $\left(\begin{array}{c}1 \\ 2 \\ 3 \end{array} \right)$ is represented by:

In [14]:
[1,2,3]

3-element Array{Int64,1}:
 1
 2
 3

* Matrices are tables of numbers. Rows are separated by a semicolon. The matrix 
$\left(\begin{array}{cc}1 & 2 \\ 3 & 4 \end{array} \right)$ is represented by:

In [15]:
[1 2; 3 4]

2×2 Array{Int64,2}:
 1  2
 3  4

The determinant  can be for example computed with `det`:

In [16]:
det([1 2; 3 4])

-2.0

* There are no "row vectors", just matrices with one row:

In [17]:
[1 2 3]

1×3 Array{Int64,2}:
 1  2  3

In [18]:
[1,2,3]

3-element Array{Int64,1}:
 1
 2
 3

### Ranges

* Consecutive elements can be written as

    first:step:last
    
* or simply, if the step is 1,
    	
    first:last
    
* Use the function `collect` or `[first:step:last;]` to transform a range into a vector:
   
Instead of typing this:  

In [19]:
[1,2,3,4,5]

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

One could simply write this as:

In [20]:
1:5

1:5

Or the full list:

In [21]:
collect(1:5)

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

Now if we need only every second element:

In [22]:
1:2:6

1:2:5

In [23]:
collect(1:2:6)

3-element Array{Int64,1}:
 1
 3
 5

Note that 6 is not part of the previous range.

## Indexing

* Consider the following vector:

In [24]:
a = [2,5,7,19,2]

5-element Array{Int64,1}:
  2
  5
  7
 19
  2

* Individual elements of a vector or matrix can be addressed by their index
* The second element of a vector `a` is for example `a[2]`

In [25]:
a[2]

5

In [26]:
length(a)

5

In [27]:
a[length(a)]

2

* The special word `end` refers to the last index.

In [28]:
a[end]

2

* One can also use a list of indexes to extract a part of the vector

In [29]:
a[[2,3,4]]

3-element Array{Int64,1}:
  5
  7
 19

In [30]:
a[[2,3,4]]

3-element Array{Int64,1}:
  5
  7
 19

* Or simply:

In [31]:
a[2:4]

3-element Array{Int64,1}:
  5
  7
 19

* The symbol colon : is a short-hand for 1:end

In [32]:
a[1:end]

5-element Array{Int64,1}:
  2
  5
  7
 19
  2

In [33]:
a[:]

5-element Array{Int64,1}:
  2
  5
  7
 19
  2

## Matrix indexing

* For matrices, two indices are used.
* The element at the second row and the first column of a matrix A is for example A[2,1]

In [34]:
A = [1 2; 3 4]


2×2 Array{Int64,2}:
 1  2
 3  4

In [35]:
A[2,1]

3

In [36]:
A[:,2]

2-element Array{Int64,1}:
 2
 4

In [37]:
A[4]

4

  
    
* If a matrix is indexed with only one subscript, the matrix is treaded as a vector where all columns are concatenated

* Julia supports also higher-dimensional arrays and indexing works similarily.



# Operators

* Scalar and matrix operations: + sum, - difference, * multiplication, / division
* Element-wise matrix operations: .* multiply element-wise, ./ divide element-wise 

## Comparison operators

 * equal (==) and different (!=)
 
 

In [38]:
2 == 1

false

In [39]:
9 == 3*3

true

In [40]:
[1 2 3] == [1 3 2]

false

In [41]:
[1 2 3] .== [1 3 2]

1×3 BitArray{2}:
 true  false  false

* Be aware of the limited precision of floating point numbers


In [42]:
2.0000000000000001 == 2

true

 * element-wise equal (.==), element-wise different (.!=)

In [43]:
[1 2 3] .== [1 3 2]

1×3 BitArray{2}:
 true  false  false

* comparision between numbers: <, >, <= (≤), => (≥)

In [44]:
30 > 25

true

* element-wise comparision between vector and matrices: .<, .>, .<= (.≤), .=> (.≥)

In [45]:
[1,2,3] .> 2

3-element BitArray{1}:
 false
 false
  true

In [46]:
[1,2,3] .> [3,1,2]

3-element BitArray{1}:
 false
  true
  true

* logical "and" (&&) logical "or" (||) (with short-circuit evaluation)

In [47]:
temperature = 30;
precipitation = 10;

if temperature > 25 && precipitation == 0
    print("go outside!")
end

* logical element-wise "and" (.&) logical element-wise "or" (.|)

* The results of such operators can also be used to index an array
    
* For example return all elements in the variable T which are greater than 10 but less than 20.
    

In [48]:
T = [27,17,20,26,32]
T[20 .< T .& T .< 30]

2-element Array{Int64,1}:
 27
 26

In [49]:
T[20 .< T .& T .< 30]

2-element Array{Int64,1}:
 27
 26

In [50]:
T .< 30

5-element BitArray{1}:
  true
  true
  true
  true
 false

In [51]:
T = [27,17,20,26,32]
T[20 .< T .& T .< 30]

2-element Array{Int64,1}:
 27
 26

* The function `find(condition)` returns the indexes of all elements where the condition is true.

In [52]:
find(20 .< T .& T .< 30)

2-element Array{Int64,1}:
 1
 4

* false is zero and true is 1. For instance to count the number of elements in the vector T which are larger than 20 one can use sum(T .> 20).

In [53]:
sum([1,2,3])

6

In [54]:
sum([1,0,1])

2

In [55]:
sum(T .> 20)

3

# Useful functions

* sin, cos, tan: trigonometric functions
* asin, acos, atan: inverse trigonometric functions
* log, log2, log10: natural, base 2 and base 10 logarithms: 
* exp: exponentiation
* abs: absolute value
* sqrt: square root
* mean: mean
* median: median
* std: standard deviation
* var: variance
* mod: modulo (useful to manipulate e.g. the longitude)
* isnan: Check if variable is NaN. Note that NaN == NaN is false!
* inv: inverse of a matrix
* sum: sum of all elements
* prod: product of all elements
* maximum,minimum: maximum,minimum value in an array
* max,min: maximum,minimum value of all arguments
* isnan: true if a value is NaN
* isinf: true if a value is Inf

These function can also operate of a given dimension: sum(array,dimension)

Find out more of these function by typing ? followed by the function name. 

In [56]:
?open

search: open isopen module_parent CompositeException operm Operators copper



```
open(filename::AbstractString, [read::Bool, write::Bool, create::Bool, truncate::Bool, append::Bool]) -> IOStream
```

Open a file in a mode specified by five boolean arguments. The default is to open files for reading only. Returns a stream for accessing the file.

```
open(filename::AbstractString, [mode::AbstractString]) -> IOStream
```

Alternate syntax for open, where a string-based mode specifier is used instead of the five booleans. The values of `mode` correspond to those from `fopen(3)` or Perl `open`, and are equivalent to setting the following boolean groups:

| Mode | Description                   |
|:---- |:----------------------------- |
| r    | read                          |
| r+   | read, write                   |
| w    | write, create, truncate       |
| w+   | read, write, create, truncate |
| a    | write, create, append         |
| a+   | read, write, create, append   |

```
open(f::Function, args...)
```

Apply the function `f` to the result of `open(args...)` and close the resulting file descriptor upon completion.

**Example**: `open(readstring, "file.txt")`

```
open(command, mode::AbstractString="r", stdio=DevNull)
```

Start running `command` asynchronously, and return a tuple `(stream,process)`.  If `mode` is `"r"`, then `stream` reads from the process's standard output and `stdio` optionally specifies the process's standard input stream.  If `mode` is `"w"`, then `stream` writes to the process's standard input and `stdio` optionally specifies the process's standard output stream.

```
open(f::Function, command, mode::AbstractString="r", stdio=DevNull)
```

Similar to `open(command, mode, stdio)`, but calls `f(stream)` on the resulting read or write stream, then closes the stream and waits for the process to complete.  Returns the value returned by `f`.


In [57]:
apropos("mean")

Base.Condition
Base.mean
Base.stdm
Base.isbits
Base.varm
Base.var
Core.String
Base.iteratorsize
Base.isleaftype
Base.mean!
Base.middle
Base.null_safe_op
Base.median
Base.iteratoreltype
Base.std
Base.Slice
Base.:∘
Base.reduce
Base.isequal
Base.Threads.atomic_cas!
Base.Multimedia.display
Base.Random.randn
Base.Random.randn!
Base.Test.test_expr!
Base.LinAlg.linreg
Base.LinAlg.sqrtm
Base.LinAlg.LAPACK.gesvx!
Base.DFT.plan_irfft
Base.DFT.plan_fft
Base.DFT.FFTW.plan_dct
Base.DFT.FFTW.plan_idct
Base.LibGit2.clone
Base.Profile.fetch
Base.SparseArrays.sprand
Compat
IJulia.set_cur_msg
FixedPointNumbers
ColorTypes.TransparentColor
ColorTypes.Colorant
ColorTypes.XYZ
Colors
Colors.weighted_color_mean
PyCall.pystealref!


In [58]:
?mean

search: mean mean! median median! RemoteChannel SegmentationFault macroexpand



```
mean(f::Function, v)
```

Apply the function `f` to each element of `v` and take the mean.

```jldoctest
julia> mean(√, [1, 2, 3])
1.3820881233139908

julia> mean([√1, √2, √3])
1.3820881233139908
```

```
mean(v[, region])
```

Compute the mean of whole array `v`, or optionally along the dimensions in `region`.

!!! note
    Julia does not ignore `NaN` values in the computation. For applications requiring the handling of missing data, the `DataArrays.jl` package is recommended.



# The file system

* On every current operating system, files are organized in a tree of directories starting from a root directory
* The absolute path of a directory or file defines which directories to follow starting from the root directory to the given directory or file
* In Linux/UNIX/Max OS X, files and directory names are separated by a slash (/), on Windows by a backslash (\\)
* In order to avoid to deal with long path names, every program has a current working directory
* The current working directory from Julia can be queried with the command `pwd()`.
* The relative path of a directory or file defines which directories to follow starting from the current directory to the given directory or file
* In relative path, two dots (`..`) represent the parent directory.
* To change the current directory, you can use the command `cd`. For Linux and Mac OS X:

```julia
cd("/home/MyDir")
``` 

Under Windows you need to you the following:

```julia
cd("C:\\Users\\MyDir")
```

Note that here two baclslashes are necessary ([why?](https://stackoverflow.com/questions/28328052/why-do-i-have-to-use-double-backslashes-for-file-paths-in-code)).

# Importing/Exporting data

## ASCII format

* To read ASCII data in Julia, tables should be saved as an ASCII text file using space or a special characters as separator. Each line corresponds to one row. Make sure that a dot is used as a decimal separator.

In [59]:
data  = readdlm("8762075.sealevel.txt",comment_char='%')

8784×8 Array{Float64,2}:
 2004.0   1.0   1.0   0.0  0.0   0.297  0.003  0.0
 2004.0   1.0   1.0   1.0  0.0   0.302  0.002  0.0
 2004.0   1.0   1.0   2.0  0.0   0.295  0.006  0.0
 2004.0   1.0   1.0   3.0  0.0   0.28   0.003  0.0
 2004.0   1.0   1.0   4.0  0.0   0.236  0.004  0.0
 2004.0   1.0   1.0   5.0  0.0   0.192  0.003  0.0
 2004.0   1.0   1.0   6.0  0.0   0.164  0.002  0.0
 2004.0   1.0   1.0   7.0  0.0   0.153  0.003  0.0
 2004.0   1.0   1.0   8.0  0.0   0.126  0.002  0.0
 2004.0   1.0   1.0   9.0  0.0   0.094  0.002  0.0
 2004.0   1.0   1.0  10.0  0.0   0.067  0.002  0.0
 2004.0   1.0   1.0  11.0  0.0   0.069  0.002  0.0
 2004.0   1.0   1.0  12.0  0.0   0.08   0.001  0.0
    ⋮                            ⋮                
 2004.0  12.0  31.0  12.0  0.0   0.078  0.003  0.0
 2004.0  12.0  31.0  13.0  0.0   0.031  0.002  0.0
 2004.0  12.0  31.0  14.0  0.0  -0.002  0.005  0.0
 2004.0  12.0  31.0  15.0  0.0  -0.025  0.001  0.0
 2004.0  12.0  31.0  16.0  0.0  -0.037  0.004  0.0
 2004.

* Saving the variable data in the file data.txt using the ASCII format

In [60]:
writedlm("data.txt",data)

## NetCDF format

* Reading a variable called `var`  from a NetCDF file

```julia
using NCDatasets
ds = Dataset("file.nc")
data = ds["var"][:];
close(ds)
```

* Writing a variable called `var` data to a NetCDF file

```julia
ds = Dataset("file.nc","c")

# Define the dimension "lon" and "lat" with the size 100 and 110 resp.
defDim(ds,"lon",100)
defDim(ds,"lat",110)


# Define the variables temperature and salinity
v = defVar(ds,"temperature",Float32,("lon","lat"))
# write a the complete data set
v[:,:] = data
close(ds)
```

# Scripts

* A series of commands can be collected in a script file
* A script file has the extension `.jl`
* How can Julia find your script file?
    * it must be either in your current work directory
    * the directory containing the script file must be added to the search path using `LOAD_PATH`. For example

```julia
push!(LOAD_PATH,"/some/path")
```

* The code in a script is executed when using `include`:

```
include("filename.jl")
```


# Functions

* Functions are similar to scripts
* Unlike scripts, functions can have input/output parameters
* For example a function calculating the speed of ocean current based on the zonal and meridional component

In [61]:
function current_speed(u,v)
   speed = sqrt(u^2 + v^2)
   return speed
end

current_speed (generic function with 1 method)

In [62]:
speed2 = current_speed(5,5)

7.0710678118654755

In [63]:
speed = current_speed(3,5)


5.830951894845301

In [64]:
P = [0,0,0,3,4,5,3,0,0]


9-element Array{Int64,1}:
 0
 0
 0
 3
 4
 5
 3
 0
 0

In [65]:
function dayswithoutrain(P)
    #....
    days = 0
    for i= 1 : length(P)
        # do something with i
        if P[i] == 0
            # count
            days = days+1
        end
        @show days
    end    
    return days
end    
days = dayswithoutrain(P)    

days = 1
days = 2
days = 3
days = 3
days = 3
days = 3
days = 3
days = 4
days = 5


5

In [66]:
using PyPlot

# Modules

Functions can be grouped into a module. 

## Installation of modules

To install a module use `Pkg.add`, for example:

In [67]:
Pkg.add("PyPlot")

INFO: Package PyPlot is already installed


Module can also be installed directly from a repository:

```julia
Pkg.clone("https://github.com/gher-ulg/divand.jl")
```

A module can be upgraded with:

In [68]:
Pkg.update("PyPlot")

INFO: Updating METADATA...
INFO: Computing changes...
INFO: No packages to install, update or remove


A no-longer used module can be removed with `Pkg.rm("ModuleName")`. 

## Using modules

To access a function (e.g. the function `plot`) inside a module (e.g. `PyPlot`) one need to load the module with `using`. The following loads the module `PyPlot`:

```julia
using PyPlot
```

Now the function `plot` can be called.
Alternatively, one can also use `import`:

```julia
import PyPlot
```
The function plot can be called as `PyPlot.plot`. The import statement is useful to indicate in the source code the origin of the different functions (and avoid possible naming conflicts).

A short summary of a module is generally available by issuing

```julia
?ModuleName
```

In [83]:
using PyPlot

In [82]:
?PyPlot

search: PyPlot



No documentation found.

Displaying the `README.md` for the module instead.

---

# The PyPlot module for Julia

This module provides a Julia interface to the [Matplotlib](http://matplotlib.org/) plotting library from Python, and specifically to the `matplotlib.pyplot` module.

PyPlot uses the Julia [PyCall](https://github.com/stevengj/PyCall.jl) package to call Matplotlib directly from Julia with little or no overhead (arrays are passed without making a copy).

This package takes advantage of Julia's [multimedia I/O](http://docs.julialang.org/en/latest/stdlib/base/#multimedia-i-o) API to display plots in any Julia graphical backend, including as inline graphics in [IJulia](https://github.com/JuliaLang/IJulia.jl). Alternatively, you can use a Python-based graphical Matplotlib backend to support interactive plot zooming etcetera.

(This PyPlot package replaces an earlier package of the same name by [Junfeng Li](https://github.com/autozimu/), which used PyPlot over a ZeroMQ socket with IPython.)

## Installation

You will need to have the Python [Matplotlib](http://matplotlib.org/) library installed on your machine in order to use PyPlot.  You can either do inline plotting with [IJulia](https://github.com/JuliaLang/IJulia.jl), which doesn't require a GUI backend, or use the Qt, wx, or GTK+ backends of Matplotlib as described below.

Once Matplotlib is installed, then you can just use `Pkg.add("PyPlot")` in Julia to install PyPlot and its dependencies.

### Automated Matplotlib installation

If you set up PyCall to use the [Conda.jl](https://github.com/Luthaf/Conda.jl) package to install a private (not in the system `PATH`) Julia Python distribution (via Miniconda), then PyPlot will automatically install Matplotlib as needed.

If you are installing PyCall and PyPlot for the first time, just do `ENV["PYTHON"]=""` before running `Pkg.add("PyPlot")`.  Otherwise, you can reconfigure PyCall to use Conda via:

```
ENV["PYTHON"]=""
Pkg.build("PyCall")
```

The next time you import `PyPlot`, it will tell Conda to install Matplotlib.

### OS X

On MacOS, you should either install [XQuartz](http://xquartz.macosforge.org/landing/) for MacOS 10.9 or later or install the [Anaconda](http://continuum.io/downloads) Python distribution in order to get a fully functional PyPlot.

MacOS 10.9 comes with Python and Matplotlib, but this version of Matplotlib defaults to with the Cocoa GUI backend, which is [not supported by PyPlot](https://github.com/stevengj/PyPlot.jl/issues/11). It also has a Tk backend, which is supported, but the Tk backend does not work unless you install XQuartz.

Alternatively, you can install the [Anaconda](http://continuum.io/downloads) Python distribution (which also includes `ipython` and other IJulia dependencies).

Otherwise, you can use the [Homebrew](http://brew.sh/) package manager:

```
brew install python gcc freetype pyqt
brew link --force freetype
export PATH="/usr/local/bin:$PATH"
export PYTHONPATH="/usr/local/lib/python2.7:$PYTHONPATH"
pip install numpy scipy matplotlib
```

(You may want to add the two `export` commands to your `~/.profile` file so that they are automatically executed whenever you start a shell.)

## Basic usage

Once Matplotlib and PyPlot are installed, and you are using a graphics-capable Julia environment such as IJulia, you can simply type `using PyPlot` and begin calling functions in the [matplotlib.pyplot](http://matplotlib.org/api/pyplot_api.html) API. For example:

```
using PyPlot
x = linspace(0,2*pi,1000); y = sin(3*x + 4*cos(2*x));
plot(x, y, color="red", linewidth=2.0, linestyle="--")
title("A sinusoidally modulated sinusoid")
```

In general, all of the arguments, including keyword arguments, are exactly the same as in Python.  (With minor translations, of course, e.g. Julia uses `true` and `nothing` instead of Python's `True` and `None`.)

The full `matplotlib.pyplot` API is far too extensive to describe here; see the [matplotlib.pyplot documentation for more information](http://matplotlib.org/api/pyplot_api.html).  The Matplotlib version number is returned by `PyPlot.version`.

### Exported functions

Only the currently documented `matplotlib.pyplot` API is exported.  To use other functions in the module, you can also call `matplotlib.pyplot.foo(...)` as `plt[:foo](...)`.  For example, `plt[:plot](x, y)` also works.  (And the raw `PyObject` for the `matplotlib` modules is also accessible as `PyPlot.matplotlib`.)

Matplotlib is somewhat inconsistent about capitalization: it has `contour3D` but `bar3d`, etcetera.  PyPlot renames all such functions to use a capital *D* (e.g. it has `hist2D`, `bar3D`, and so on).

You must also use `plt` to access some functions that conflict with built-in Julia functions.  In particular `plt[:hist]`, `plt[:xcorr]`, and `plt[:isinteractive]` must be used to access `matplotlib.pyplot.hist` etcetera.

If you wish to access *all* of the PyPlot functions exclusively through `plt.somefunction(...)`, as is conventional in Python, you can do `import PyPlot; const plt = PyPlot` instead of `using PyPlot`.

### Figure objects

You can get the current figure as a `Figure` object (a wrapper around `matplotlib.pyplot.Figure`) by calling `gcf()`.  

The `Figure` type supports Julia's [multimedia I/O API](http://docs.julialang.org/en/latest/stdlib/base/#multimedia-i-o), so you can use `display(fig)` to show a `fig::PyFigure` and `show(io, mime, fig)` (or `writemime` in Julia 0.4) to write it to a given `mime` type string (e.g. `"image/png"` or `"application/pdf"`) that is supported by the Matplotlib backend.

## Non-interactive plotting

If you use PyPlot from an interactive Julia prompt, such as the Julia [command-line prompt](http://docs.julialang.org/en/latest/manual/interacting-with-julia/) or an IJulia notebook, then plots appear immediately after a plotting function (`plot` etc.) is evaluated.

However, if you use PyPlot from a Julia script that is run non-interactively (e.g. `julia myscript.jl`), then Matplotlib is executed in [non-interactive mode](http://matplotlib.org/faq/usage_faq.html#what-is-interactive-mode): a plot window is not opened until you run `show()` (equivalent to `plt.show()` in the Python examples).

## Interactive versus Julia graphics

PyPlot can use any Julia graphics backend capable of displaying PNG, SVG, or PDF images, such as the IJulia environment.  To use a different backend, simply call `pushdisplay` with the desired `Display`; see the [Julia multimedia display API](http://docs.julialang.org/en/latest/stdlib/io-network/#multimedia-i-o) for more detail.

On the other hand, you may wish to use one of the Python Matplotlib backends to open an interactive window for each plot (for interactive zooming, panning, etcetera).  You can do this at any time by running:

```
pygui(true)
```

to turn on the Python-based GUI (if possible) for subsequent plots, while `pygui(false)` will return to the Julia backend.  Even when a Python GUI is running, you can display the current figure with the Julia backend by running `display(gcf())`.

If no Julia graphics backend is available when PyPlot is imported, then `pygui(true)` is the default.

### Choosing a Python GUI toolkit

Only the [Tk](http://www.tcl.tk/), [wxWidgets](http://www.wxwidgets.org/), [GTK+](http://www.gtk.org/) (version 2 or 3), and [Qt](http://qt-project.org/) (version 4 or 5; via the PyQt5,  [PyQt4](http://wiki.python.org/moin/PyQt4) or [PySide](http://qt-project.org/wiki/PySide)), Python GUI backends are supported by PyPlot.  (Obviously, you must have installed one of these toolkits for Python first.)  By default, PyPlot picks one of these when it starts up (based on what you have installed), but you can force a specific toolkit to be chosen by importing the PyCall module and using its `pygui` function to set a Python backend *before* importing PyPlot:

```
using PyCall
pygui(gui)
using PyPlot
```

where `gui` can currently be one of `:tk`, `:gtk3`, `:gtk`, `:qt5`, `:qt4`, `:qt`, or `:wx`. You can also set a default via the Matplotlib `rcParams['backend']` parameter in your [matplotlibrc](http://matplotlib.org/users/customizing.html) file.

## Color maps

The PyPlot module also exports some functions and types based on the [matplotlib.colors](http://matplotlib.org/api/colors_api.html) and [matplotlib.cm](http://matplotlib.org/api/cm_api.html) modules to simplify management of color maps (which are used to assign values to colors in various plot types).  In particular:

  * `ColorMap`: a wrapper around the [matplotlib.colors.Colormap](http://matplotlib.org/api/colors_api.html#matplotlib.colors.Colormap) type.  The following constructors are provided:

      * `ColorMap{T<:Colorant}(name::String, c::AbstractVector{T}, n=256, gamma=1.0)` constructs an `n`-component colormap by [linearly interpolating](http://matplotlib.org/api/colors_api.html#matplotlib.colors.LinearSegmentedColormap) the colors in the array `c` of `Colorant`s (from the [ColorTypes.jl](https://github.com/JuliaGraphics/ColorTypes.jl) package).  If you want a `name` to be constructed automatically, call `ColorMap(c, n=256, gamma=1.0)` instead.  Alternatively, instead of passing an array of colors, you can pass a 3- or 4-column matrix of RGB or RGBA components, respectively (similar to [ListedColorMap](http://matplotlib.org/api/colors_api.html#matplotlib.colors.ListedColormap) in Matplotlib).
      * Even more general color maps may be defined by passing arrays of (x,y0,y1) tuples for the red, green, blue, and (optionally) alpha components, as defined by the [matplotlib.colors.LinearSegmentedColormap](http://matplotlib.org/api/colors_api.html#matplotlib.colors.LinearSegmentedColormap) constructor, via: `ColorMap{T<:Real}(name::String, r::AbstractVector{(T,T,T)}, g::AbstractVector{(T,T,T)}, b::AbstractVector{(T,T,T)}, n=256, gamma=1.0)` or `ColorMap{T<:Real}(name::String, r::AbstractVector{(T,T,T)}, g::AbstractVector{(T,T,T)}, b::AbstractVector{(T,T,T)}, alpha::AbstractVector{(T,T,T)}, n=256, gamma=1.0)`
      * `ColorMap(name::String)` returns an existing (registered) colormap, equivalent to [matplotlib.cm.get_cmap](http://matplotlib.org/api/cm_api.html#matplotlib.cm.get_cmap)(`name`).
      * `matplotlib.colors.Colormap` objects returned by Python functions are automatically converted to the `ColorMap` type.
  * `get_cmap(name::String)` or `get_cmap(name::String, lut::Integer)` call the [matplotlib.cm.get_cmap](http://matplotlib.org/api/cm_api.html#matplotlib.cm.get_cmap) function.
  * `register_cmap(c::ColorMap)` or `register_cmap(name::String, c::ColorMap)` call the [matplotlib.cm.register_cmap](http://matplotlib.org/api/cm_api.html#matplotlib.cm.register_cmap) function.
  * `get_cmaps()` returns a `Vector{ColorMap}` of the currently registered colormaps.

Note that, given an SVG-supporting display environment like IJulia, `ColorMap` and `Vector{ColorMap}` objects are displayed graphically; try `get_cmaps()`!

## 3d Plotting

The PyPlot package also imports functions from Matplotlib's [mplot3d](http://matplotlib.org/mpl_toolkits/mplot3d/) toolkit. Unlike Matplotlib, however, you can create 3d plots directly without first creating an [Axes3d](http://matplotlib.org/mpl_toolkits/mplot3d/api.html#axes3d) object, simply by calling one of: `bar3D`, `contour3D`, `contourf3D`, `plot3D`, `plot_surface`, `plot_trisurf`, `plot_wireframe`, or `scatter3D` (as well as `text2D`, `text3D`), exactly like the correspondingly named methods of [Axes3d](http://matplotlib.org/mpl_toolkits/mplot3d/api.html#axes3d). We also export the Matlab-like synonyms `surf` for `plot_surface` (or `plot_trisurf` for 1d-array arguments) and `mesh` for `plot_wireframe`.  For example, you can do:

```
surf(rand(30,40))
```

to plot a random 30×40 surface mesh.

You can also explicitly create a subplot with 3d axes via, for example, `subplot(111, projection="3d")`, exactly as in Matplotlib. The `Axes3D` constructor and the [art3D](http://matplotlib.org/mpl_toolkits/mplot3d/api.html#art3d) module are also exported.

## LaTeX plot labels

Matplotlib allows you to [use LaTeX equations in plot labels](http://matplotlib.org/users/mathtext.html), titles, and so on simply by enclosing the equations in dollar signs (`$ ... $`) within the string.  However, typing LaTeX equations in Julia string literals is awkward because escaping is necessary to prevent Julia from interpreting the dollar signs and backslashes itself; for example, the LaTeX equation `$\alpha + \beta$` would be the literal string `"\$\\alpha + \\beta\$"` in Julia.

To simplify this, PyPlot uses the [LaTeXStrings package](https://github.com/stevengj/LaTeXStrings.jl) to provide a new `LaTeXString` type that be constructed via `L"...."` without escaping backslashes or dollar signs.  For example, one can simply write `L"$\alpha + \beta$"` for the abovementioned equation, and thus you can do things like:

```
title(L"Plot of $\Gamma_3(x)$")
```

If your string contains *only* equations, you can omit the dollar signs, e.g. `L"\alpha + \beta"`, and they will be added automatically. As an added benefit, a `LaTeXString` is automatically displayed as a rendered equation in IJulia.  See the LaTeXStrings package for more information.

## SVG output in IJulia

By default, plots in IJulia are sent to the notebook as PNG images. Optionally, you can tell PyPlot to display plots in the browser as [SVG](https://en.wikipedia.org/wiki/Scalable_Vector_Graphics) images, which have the advantage of being resolution-independent (so that they display without pixellation at high-resolutions, for example if you convert an IJulia notebook to PDF), by running:

```
PyPlot.svg(true)
```

This is not the default because SVG plots in the browser are much slower to display (especially for complex plots) and may display inaccurately in some browsers with buggy SVG support.  The `PyPlot.svg()` method returns whether SVG display is currently enabled.

Note that this is entirely separate from manually exporting plots to SVG or any other format.  Regardless of whether PyPlot uses SVG for browser display, you can export a plot to SVG at any time by using the Matplotlib [savefig](http://matplotlib.org/api/pyplot_api.html#matplotlib.pyplot.savefig) command, e.g. `savefig("plot.svg")`.

## Author

This module was written by [Steven G. Johnson](http://math.mit.edu/~stevenj/).


# Dates

* Julia has a structure called `DateTime` to represent a date and time.

In [70]:
lastsecond = DateTime(1999,12,31,23,59,59)

1999-12-31T23:59:59

* The difference between two `DateTime`s returns a structure representing the number of milliseconds.

In [71]:
DateTime(2001,1,1)

2001-01-01T00:00:00

In [72]:
DateTime(2001,1,1) - DateTime(2000,1,1)

31622400000 milliseconds

* Convert this in days:

In [73]:

Dates.Day(DateTime(2001,1,1) - DateTime(2000,1,1))

366 days

* add a duration to a date

In [74]:
DateTime(2000,1,1) + Dates.Day(366)

2001-01-01T00:00:00

In [75]:
now()

2018-03-06T17:01:07.132

In [76]:
Dates.value(DateTime(2018,9,7) - now()) / 1000 / 60 / 60 / 24

184.29088960648144

In [77]:
Dates.value(DateTime(2017,9,7) - now()) /(24*60*60*1000)

-180.7091105324074

In how many days is your next birthday?

## Loops

* Let your computer do repetitive tasks!
* Loops have a counter which takes successively all elements of a row vector

In [78]:
    for i = [1 2 10 20]
      @show i
    end

i = 1
i = 2
i = 10
i = 20


* Loops are often used with a range of values

In [79]:
for i = 1:5
  @show i
end

i = 1
i = 2
i = 3
i = 4
i = 5


* Explicit loops can sometimes be avoided:
* For example, sum all integer from 1 to 10

In [80]:
total = 0;
for i = 1:10
   total = total + i;
end
total

55

Can simply be computed as `sum(1:10)`.

# if-statement

* Sometimes your code needs to behave differently depending on some conditions.

* if-statement has the following structure.

```julia
if some_conditions
  # do something
else
  # do something else
end
```
The else section can be omitted.

For example.

```julia
if x < 0
   x = -x;
end
```

* Which Julia function implements the last code example?